version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - arangodb
  arangodb:
    image: arangodb/arangodb:3.7.10
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=dbpass